apiVersion: v1
kind: Service
metadata:
  name: botfly-svc
  labels:
    app: botfly-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: web
    - port: 50051
      targetPort: 50051
      name: grpc
  selector:
    app: botfly-svc
